//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_PRODUCTION.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string DoctorName { get; set; }
        public string BookingDate { get; set; }
        public string Bookingtime { get; set; }
        public string Description { get; set; }
        public string Department { get; set; }
        public string DoctorAddress { get; set; }
        public string UserName { get; set; }
    }
}
